### ISSUE TITLE
add SingleCellMultiModal vignettes and suggests

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayWorkshop#6]
Would like to be able to include SingleCellMultiModal in this workshop too. So far at a minimum, need to add the following to be able to run SingleCellMultiModal vignettes:
1. the vignettes
2. BiocStyle, scater, scran, uwot

**Comment by LiNk-NY** [comment]
I've added an intro vignette to `SingleCellMultiModal` to the workshop `articles/` and referred readers to browsing the vignettes in the SCMM package.
