### ISSUE TITLE
"Build Your First MAE" Shiny app is very slow

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayWorkshop#8]
Brought to my attention by a student at CSAMA today in Brixen, the [Build Your First MAE](https://waldronlab.io/MultiAssayWorkshop/tutorials/Exercise_MultiAssay.html) app takes minutes to load. Maybe it would it run better on https://shiny.sph.cuny.edu/ ? Otherwise, I would just remove it from the GitHub Pages menu because it isn't very usable at this speed of loading.

**Comment by LiNk-NY** [comment]
That's strange. I just clicked on it and it took 2 seconds to load. 
Perhaps it takes longer to load from a dormant state. 
I can look into moving it over. Thanks!

**Comment by LiNk-NY** [comment]
5a6357ca4befa78f2915b85fb598195c01c12850

**Comment by lwaldron** [comment]
And for me now at my hotel it did too. I wonder if it was a firewall issue - I'll test the new setup when I'm back at the conference venue.

**Comment by LiNk-NY** [comment]
If you tried this a few minutes ago, you should've gotten the sph shiny app to load. Perhaps it takes longer across the Atlantic?

**Comment by lwaldron** [comment]
> And for me now at my hotel it did too. I wonder if it was a firewall issue - I'll test the new setup when I'm back at the conference venue.

Actually I meant it was fast for me at the hotel, so I thought it might have been a firewall issue at the conference. Today it is fast at the conference too.
